$("#submit").on('click', function(e){
	e.preventDefault();
	var storeIdeaTitle = $('#title-input').val();
	var storeIdeaContent = $('#content-input').val();
	var card = new Card(storeIdeaTitle, storeIdeaContent);
	var stringCard = JSON.stringify(card);
	localStorage.setItem(card.id, stringCard);
	console.log(card);
	console.log(stringCard);

})

function Card(storeIdeaTitle, storeIdeaContent) {
	this.title = storeIdeaTitle;
	this.body = storeIdeaContent;
	this.quality = undefined;
	this.id = localStorage.length;
}

// as the key local storage key: Have the card.id be generated by localStorage.length only problem is that it starts at zero... then use card.id as the local storage key.
//
// or have the localStorage.setItem key be storeIdeaTitle. I tried it both ways and it works.
